job('First-Maven_Project-Via-DSL') {
    description("First Maven job generated by the DSL on ${new Date()}, the project is a small Maven project hosted on github")
    scm {
        git("https://github.com/jnybrahma/learn_maven.git", '*/master')
    }
    triggers {
        scm('* * * * *')
    }
	tools {
			maven 'LocalMaven'
	}
    steps {
        maven('clean package', 'single-module/pom.xml')
    }
    publishers {
        //archive the war file generated
        archiveArtifacts '**/*.jar'
    }
}